/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package figurasCirculos;

public class TableroBee extends javax.swing.JFrame {

    /**
     * Creates new form TableroBee
     */
    public TableroBee() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        tableroBee = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Bee");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 11, -1, -1));

        javax.swing.GroupLayout tableroBeeLayout = new javax.swing.GroupLayout(tableroBee);
        tableroBee.setLayout(tableroBeeLayout);
        tableroBeeLayout.setHorizontalGroup(
            tableroBeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 960, Short.MAX_VALUE)
        );
        tableroBeeLayout.setVerticalGroup(
            tableroBeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );

        getContentPane().add(tableroBee, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 960, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        
        
        BeeClass.HacerArcoSky(tableroBee.getGraphics(), 180, 20, 120, 180, 20, 360);
        BeeClass.HacerArcoSky(tableroBee.getGraphics(), 300, 20, 120, 180, 20, 360);
        
        //OJOS
        BeeClass.HacerCirculoAmarillo(tableroBee.getGraphics(), 100, 140, 420, 280);
        BeeClass.HacerCirculoNegro(tableroBee.getGraphics(), 400, 130, 170, 170);
        BeeClass.HacerCirculo(tableroBee.getGraphics(), 411, 140, 150, 150);
        BeeClass.HacerCirculoNegro(tableroBee.getGraphics(), 460, 190, 50, 50);
        //FIN OJOS
        BeeClass.HacerCirculoNegro(tableroBee.getGraphics(), 300, 130, 170, 170);
        BeeClass.HacerCirculo(tableroBee.getGraphics(), 311, 140, 150, 150);
        BeeClass.HacerCirculoNegro(tableroBee.getGraphics(), 360, 190, 50, 50);
        BeeClass.HacerArco(tableroBee.getGraphics(), 200, 470, 80, 80, 90, 180);
        int [] q = {240, 510, 510, 240};
        int [] w = {470, 470, 550 , 550};
                
        BeeClass.HacerPoligono(tableroBee.getGraphics(), q , w , 4);
        //PUNTA DEL LAPIZ
        int [] e = {510, 540, 510};
        int [] r = {470, 510, 550};
        BeeClass.HacerPoligonoNegro(tableroBee.getGraphics(), e , r , 3);
        //FIN PUNTA DEL LAPIZ
        BeeClass.HacerLinea(tableroBee.getGraphics(), 240, 475, 240 , 545);
        BeeClass.HacerArcoNegro(tableroBee.getGraphics(), 380, 220, 20, 30, 90, 180);
        
        
        
        
        
       
        
        
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        TableroBee miFormulario = new TableroBee();
        miFormulario.setVisible(true);
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel tableroBee;
    // End of variables declaration//GEN-END:variables
}
