/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package primitivas2d;

/**
 *
 * @author Ricardo Rodriguez
 */
public class DibujaGraficasView extends javax.swing.JFrame {

    /**
     * Creates new form DibujaGraficasView
     */
    public DibujaGraficasView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDibujarLinea = new javax.swing.JButton();
        tablero = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("tablero");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnDibujarLinea.setText("Bruja");
        btnDibujarLinea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDibujarLineaMouseClicked(evt);
            }
        });
        btnDibujarLinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDibujarLineaActionPerformed(evt);
            }
        });
        getContentPane().add(btnDibujarLinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        tablero.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(tablero, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 820, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDibujarLineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDibujarLineaActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnDibujarLineaActionPerformed

    private void btnDibujarLineaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDibujarLineaMouseClicked
        // TODO add your handling code here:
        
        int [] x ={350, 380, 360,420, 290 };
        int [] y = {10, 50, 50, 130, 130};
        int [] xcinSomb = {315, 385, 410, 293 };
        int [] ycinSomb = {80, 80, 120, 120};
    
    //SOMBRERO    
        Dibujo.HacerPoligonoBlue(tablero.getGraphics(), x, y, 5  );
        Dibujo.HacerCuadroBlue(tablero.getGraphics(), 240, 130, 230, 10);
        Dibujo.HacerPoligonoNegro(tablero.getGraphics(),xcinSomb, ycinSomb, 4);
        Dibujo.HacerCuadroAmarillo(tablero.getGraphics(), 330, 80, 40, 40);
        Dibujo.HacerCuadroNegro(tablero.getGraphics(), 338, 88, 25, 25);
     //FIN SOMBRERO  
      //CABELLO IZQUIERDO
      Dibujo.HacerLinea(tablero.getGraphics(), 293, 135, 205, 210);
      Dibujo.HacerLinea(tablero.getGraphics(), 330, 135, 250, 270);
      Dibujo.HacerLinea(tablero.getGraphics(), 230, 255, 250, 270);
      Dibujo.HacerLinea(tablero.getGraphics(), 230, 255, 270, 190);
      Dibujo.HacerLinea(tablero.getGraphics(), 270, 190, 215, 255);
      Dibujo.HacerLinea(tablero.getGraphics(), 215, 255, 220, 230);
      Dibujo.HacerLinea(tablero.getGraphics(), 220, 230, 260, 180);
      Dibujo.HacerLinea(tablero.getGraphics(), 190, 240, 260, 180);
      Dibujo.HacerLinea(tablero.getGraphics(), 190, 240, 205, 210);
      //FIN CABELLO IZQUIERDO
      
       //CABELLO DERECHO
      Dibujo.HacerLinea(tablero.getGraphics(), 370, 135, 450, 270);
      Dibujo.HacerLinea(tablero.getGraphics(), 397, 135, 510, 210);
      Dibujo.HacerLinea(tablero.getGraphics(), 470, 255, 450, 270);
      Dibujo.HacerLinea(tablero.getGraphics(), 470, 255, 430, 190);
      Dibujo.HacerLinea(tablero.getGraphics(), 510, 255, 430, 190);
      Dibujo.HacerLinea(tablero.getGraphics(), 512, 240, 510, 255);
      Dibujo.HacerLinea(tablero.getGraphics(), 512, 240, 465, 200);
      Dibujo.HacerLinea(tablero.getGraphics(), 545, 250, 465, 200);
      Dibujo.HacerLinea(tablero.getGraphics(), 545, 250, 510, 210);
     //FIN CABELLO DERECHO
        //CARA
        int [] u ={285, 327, 373, 415, 373, 327 };
        int [] p = {210, 140, 140, 210, 250, 250 };
       Dibujo.HacerPoligonoVerde(tablero.getGraphics(), u , p , 6);
       Dibujo.HacerCuadro(tablero.getGraphics(), 325, 160, 20, 20);
       Dibujo.HacerCuadro(tablero.getGraphics(), 360, 160, 20, 20);
       Dibujo.HacerCuadroNegro(tablero.getGraphics(), 330, 165, 10, 10);
       Dibujo.HacerCuadroNegro(tablero.getGraphics(), 365, 165, 10, 10);
       Dibujo.HacerLinea(tablero.getGraphics(), 330, 190,365, 190);
       Dibujo.HacerLinea(tablero.getGraphics(), 330, 190,310, 205);
       Dibujo.HacerLinea(tablero.getGraphics(), 310, 205,355, 205);
       
       //BOCA
       Dibujo.HacerLinea(tablero.getGraphics(), 333, 233,368, 233);
       Dibujo.HacerLinea(tablero.getGraphics(), 333, 233,325, 225);
       Dibujo.HacerLinea(tablero.getGraphics(), 376, 225,368, 233);       
        //FIN CARA
        //VESTIDO
        int [] q = {327,373,415,295 };
        int [] w = {250,250,380,380 };
        Dibujo.HacerPoligonoBlue(tablero.getGraphics(), q, w, 4  );
        //FIN VESTIDO
        //ESCOBA
          int [] e ={490, 518, 625, 625, 518, 490 };
        int [] r = {373, 320, 320, 420, 420, 373 };
       Dibujo.HacerPoligonoMarron(tablero.getGraphics(), e , r , 5);
        Dibujo.HacerCuadroMarron(tablero.getGraphics(), 190, 370, 109, 10);
        Dibujo.HacerCuadroMarron(tablero.getGraphics(), 413, 370, 80, 10);        
        //FIN ESCOBA
        //BRAZOS
          int [] t = {255,327,335,270 };
        int [] i = {340,250,260,360 };
        Dibujo.HacerPoligonoBlue(tablero.getGraphics(), t, i, 4  );
        
         int [] a ={255, 270, 270, 230, 230 };
        int [] s = {340, 360, 373, 373, 360 };
       Dibujo.HacerPoligonoVerde(tablero.getGraphics(), a , s , 5);
        
         int [] d ={373, 425, 475, 480, 425, 373 };
        int [] g = {250, 270, 290, 305, 295, 270 };
       Dibujo.HacerPoligonoBlue(tablero.getGraphics(), d , g , 6);
       
       int [] z ={475, 475, 482, 482, 510, 518, 480 };
        int [] c = {290, 265, 265, 280, 265, 290, 305 };
       Dibujo.HacerPoligonoVerde(tablero.getGraphics(), z , c , 7);
        
        //FIN BRAZOS
      //PIERNAS
        int [] v = {360, 405, 420, 435, 435, 400 };
        int [] b = {380, 380, 400, 400, 420, 420 };
       Dibujo.HacerPoligonoVerde(tablero.getGraphics(), v , b , 6);
      
      int [] n = {305, 350, 365, 380, 380, 345 };
      int [] m = {380, 380, 425, 425, 445, 445 };
       Dibujo.HacerPoligonoVerde(tablero.getGraphics(), n , m , 6);
       Dibujo.HacerCuadroAmarillo(tablero.getGraphics(), 380, 425, 10, 20);
       Dibujo.HacerCuadroAmarillo(tablero.getGraphics(), 435, 400, 10, 20);
       
        int [] j = {390, 430, 430, 410, 390 };
       int [] k = {425, 425, 470, 445, 445 };
       Dibujo.HacerPoligonoNegro(tablero.getGraphics(), j , k , 5);
      
        int [] f = {445, 485, 485, 465, 445 };
       int [] h = {400, 400, 445, 420, 420 };
       Dibujo.HacerPoligonoNegro(tablero.getGraphics(), f , h , 5);
      //FIN PIERNAS
      //LUNA
        int [] qw = {600, 630, 660, 690, 690, 660, 630, 600, 630, 645 ,645 };
        int [] wq = { 10,  10,  30, 60, 110, 140, 150, 150, 130, 100, 70  };
       
       Dibujo.HacerPoligonoYellow(tablero.getGraphics(), qw , wq , 11);
      
      //FIN LUNA
      
    }//GEN-LAST:event_btnDibujarLineaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        DibujaGraficasView miFormulario = new DibujaGraficasView();
        miFormulario.setVisible(true);
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DibujaGraficasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DibujaGraficasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DibujaGraficasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DibujaGraficasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DibujaGraficasView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDibujarLinea;
    private javax.swing.JPanel tablero;
    // End of variables declaration//GEN-END:variables
}
